include $(TOPDIR)/rules.mk

PKG_VERSION:=2026.7.25
PKG_RELEASE:=10

LUCI_TITLE:=LuCI Support for MihomoX
LUCI_DEPENDS:=+luci-base +mihomox +ucode-mod-resolv

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
