include $(TOPDIR)/rules.mk

PKG_VERSION:=2026.8.30
PKG_RELEASE:=1

LUCI_TITLE:=LuCI Support for MihomoX
LUCI_DEPENDS:=
LUCI_EXTRA_DEPENDS:=luci-base (>=0), mihomox (>=0), ucode-mod-resolv (>=0)

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
