name: release-packages
# mihomox-actions-index: force workflow registration

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  release:
    name: x86_64-${{ matrix.branch }} release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        branch:
          - openwrt-23.05
          - openwrt-24.10
          - openwrt-25.12
          - SNAPSHOT

    steps:
      - name: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: build
        uses: openwrt/gh-action-sdk@797d0e3d0eb13b355c3447f60d0179d4b43089e2 # main
        env:
          ARCH: x86_64-${{ matrix.branch == 'openwrt-23.05' && '23.05.5' || matrix.branch }}
          FEEDNAME: mihomox
          PACKAGES: mihomox luci-app-mihomox
          INDEX: 1
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NO_REFRESH_CHECK: true

      - name: compress
        run: |
          tar -c -z -f mihomox_x86_64-${{ matrix.branch }}.tar.gz -C bin/packages/x86_64/mihomox .
          mkdir -p public/${{ matrix.branch }}/x86_64
          mv bin/packages/x86_64/mihomox public/${{ matrix.branch }}/x86_64
          tar -c -z -f feed_mihomox_x86_64-${{ matrix.branch }}.tar.gz public/${{ matrix.branch }}/x86_64

      - if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
        name: release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          files: |
            mihomox_x86_64-${{ matrix.branch }}.tar.gz

      - name: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: feed_mihomox_x86_64-${{ matrix.branch }}
          path: feed_mihomox_x86_64-${{ matrix.branch }}.tar.gz

  feed:
    needs: release
    name: feed
    runs-on: ubuntu-latest

    steps:
      - name: download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: feed_mihomox_*
          merge-multiple: true

      - name: uncompress
        run: |
          for file in feed_mihomox_*.tar.gz; do tar -x -z -f "$file"; done

      - name: prepare
        run: |
          echo "${{ secrets.KEY_BUILD_PUB }}" > public/key-build.pub
          echo "${{ secrets.PUBLIC_KEY }}" > public/public-key.pem
          tree --dirsfirst --sort name -P '*.apk|*.ipk' --prune --noreport -H "" -T "MihomoX's Feed" --charset utf-8 -o public/index.html public
          sed -i '/<p class="VERSION">/,/<\/p>/d' public/index.html

      - name: feed
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy public --project-name=mihomox
